version: '3.2'

volumes:
  cookbook-postgres:
    driver: local

services:
  postgres:
    image: postgres:9.6
    container_name: cookbook-postgres
    volumes:
      - type: volume
        source: cookbook-postgres
        target: /var/lib/postgresql/dataConfig
    environment:
      POSTGRES_DB: cookbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

# jdbc:postgresql://localhost:5432/cookbook