server:
  port: 8081
#  servlet:
#    context-path: /cookbook

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cookbook
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format-sql: true
  mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtps
    username: name@gmail.com
    password: password
    properties:
      mail:
        transport:
          protocol: smtps
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000

springdoc:
  swagger-ui:
    path: /api_doc.html
#   operationsSorter: method

ws:
  app_prefix: /app
  broker: /cookbook
  endpoint: /stomp
  new_recipes: /new
  ratings: /topic/ratings
  user_prefix: /users


